from collections import deque
queue = deque(['Eric','John','Michael'])
queue.append('Terry')
queue.append('Graham')
print(queue)
temp = queue.popleft()
print(temp)
temp = queue.popleft()
print(temp)
print(queue)